### ISSUE TITLE
Regarding the issue of Tmap generation

### ISSUE THREAD

**Issue by L-xia-C** [marukosan93/RS-rPPG#2]
I have generated "mstmap.npy" and "bvp.npy" for each sample according to the CVD method. However, I encountered some issues when using create_tmaps_VIPL.py to generate the Tmap. (Additionally, the README mentions a shell script file “create_tmaps_VIPL.sh,” but there is only the create_tmaps_VIPL.py file in the project.)
![image](https://github.com/user-attachments/assets/60aa4a2c-eb20-4bdc-90b2-bc0c7f69947e)

I’m quite confused about the meaning of `temp` and `mstmap`. It seems that `filename` refers to "mstmap.npy", but `mstmap = np.load(filename.replace("temp","mstmap"))[:,:,0:3]` makes things even more confusing. 
I would like to know if `temp` and `mstmap` are both referring to "mstmap.npy".
Thank you!

**Comment by L-xia-C** [comment]
Additionally, there is a minor issue when generating mstmap in CVD-Physiological-Measurement. CVD sliced the mstmap, then applied smoothing and normalization to the segments. The corresponding MATLAB code is as follows:
```matlab
for idx = 1:size(final_signal,1)
    for c = 1:channel_num
        temp = final_signal(idx,:,c);
        temp = movmean(temp, 3);
        final_signal1(idx,:,c) = (temp - min(temp)) / (max(temp) - min(temp)) * 255;
    end
end
```
I noticed that the filt_map function in create_tmaps_VIPL.py implements a similar functionality. So, during the generation of mstmap, is there only one normalization step that occurs in the filt_map function?

**Comment by marukosan93** [comment]
Hi, for your first comment, "temp" and "mstmap" are the same. "temp" was just just some legacy code left over from experimenting with different maps in the beginning. So they are the same. For your second comment, compared to CVD matlab code instead of moving average we bandpass filter to smooth the signals, and the normalization step is the exact same. During the generation they are normalised and saved, and also in the dataloader when smaller windows are loaded.

**Comment by L-xia-C** [comment]
Thank you for your clear and accurate explanation.
